version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: avatargamer_db
    environment:
      POSTGRES_DB: avatargamer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d avatargamer"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    container_name: avatargamer_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_JWT_SECRET: "change-this-in-prod-32-bytes-min"
      APP_JWT_ISSUER: "avatargamer"
      APP_JWT_ACCESS_TTL: "PT30M"      # 30 minutos
      APP_JWT_REFRESH_TTL: "P7D"       # 7 días
    ports:
      - "8080:8080"

volumes:
  db_data:
