spring:
  datasource:
    url: jdbc:h2:mem:avatargamer;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update
  h2:
    console.enabled: true
    console.path: /h2-console
