FROM python:3.11-slim

# Evita archivos .pyc y buffer en consola
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Instala dependencias necesarias para psycopg2 y Pillow
RUN apt-get update && apt-get install -y \
    build-essential libpq-dev gettext \
    && rm -rf /var/lib/apt/lists/*

# Copia requirements y los instala
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Crea usuario sin privilegios
RUN useradd -m runner
USER runner

EXPOSE 8000

CMD ["bash", "-lc", "echo 'Use entrypoint.sh desde docker-compose'"]
