# Generated by Django 5.2.7 on 2025-10-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_convers_c2caf0_idx',
            old_name='apps_chat_c_convers_d111d3_idx',
        ),
    ]
