# Generated by Django 5.2.7 on 2025-10-09 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_operatoruserlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=16)),
                ('message', models.TextField(blank=True, help_text='Mensaje opcional del operador para el usuario', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_link_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_link_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='operatoruserlink',
            name='link_request',
            field=models.OneToOneField(blank=True, help_text='Solicitud que originó este vínculo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.linkrequest'),
        ),
        migrations.AddIndex(
            model_name='linkrequest',
            index=models.Index(fields=['operator', 'status'], name='accounts_li_operato_8ad747_idx'),
        ),
        migrations.AddIndex(
            model_name='linkrequest',
            index=models.Index(fields=['user', 'status'], name='accounts_li_user_id_1af532_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linkrequest',
            unique_together={('operator', 'user', 'status')},
        ),
    ]
